# Generated by Django 2.0 on 2017-12-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTable',
        ),
    ]
