# Generated by Django 2.2.5 on 2020-02-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200119_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='category',
            new_name='category_2',
        ),
    ]
