# Generated by Django 3.0 on 2019-12-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64, verbose_name='product name')),
                ('product_desc', models.CharField(max_length=200, verbose_name='product desc')),
                ('product_owner', models.CharField(max_length=200, verbose_name='product owner')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='create time')),
            ],
            options={
                'verbose_name': 'product management',
                'verbose_name_plural': 'product_management',
            },
        ),
    ]
