# Generated by Django 3.0 on 2020-01-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=64, verbose_name='bug name')),
                ('bug_detail', models.CharField(max_length=200, verbose_name='bug detail')),
                ('bug_status', models.CharField(choices=[('opened', 'opened'), ('resovled', 'resolved'), ('fixed', 'fixed'), ('closed', 'closed')], default='opened', max_length=64, null=True, verbose_name='status')),
                ('bug_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=8, null=True, verbose_name='severity')),
                ('bug_creator', models.CharField(max_length=64, verbose_name='creator')),
                ('bug_assignee', models.CharField(max_length=64, verbose_name='assignee')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='created time')),
                ('Product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'bug management',
                'verbose_name_plural': 'bug management',
            },
        ),
    ]
