# Generated by Django 3.0 on 2020-01-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='bug_status',
            field=models.CharField(choices=[('opened', 'opened'), ('resolved', 'resolved'), ('fixed', 'fixed'), ('closed', 'closed')], default='opened', max_length=64, null=True, verbose_name='status'),
        ),
    ]
