myTasks = { 'itl_generic': { 'DNSC': [ ['build', 'helix-build-slave', 3250, u'SUCCESS'],
                             ['test', 'helix-test-itl_generic', 1316, u'SUCCESS'],
                             ['report', 'helix-report', 2362, u'SUCCESS'],
                             ['retest', 'na', 'na', 'SUCCESS'],
                             ['rereport', 'na', 'na', 'SUCCESS']],
                   'FTP': [ ['build', 'helix-build-slave', 3254, u'SUCCESS'],
                            ['test', 'helix-test-itl_generic', 1317, u'SUCCESS'],
                            ['report', 'helix-report', 2364, u'SUCCESS'],
                            ['retest', 'na', 'na', 'SUCCESS'],
                            ['rereport', 'na', 'na', 'SUCCESS']],
                   'IKE-ADVANCED': [ ['build', 'helix-build-slave', 3258, u'SUCCESS'],
                                     ['test', 'helix-test-itl_generic', 1318, u'FAILURE'],
                                     ['report', 'helix-report', 2369, u'SUCCESS'],
                                     ['retest', 'helix-test-itl_generic', 1320, u'FAILURE'],
                                     ['rereport', 'helix-report', 2374, u'SUCCESS']],
                   'IPNET': [ ['build', 'helix-build-slave', 3262, u'SUCCESS'],
                              ['test', 'helix-test-itl_generic', 1319, u'FAILURE'],
                              ['report', 'helix-report', 2373, u'SUCCESS'],
                              ['retest', 'helix-test-itl_generic', 1321, u'SUCCESS'],
                              ['rereport', 'helix-report', 2379, u'SUCCESS']],
                   'IPNET-IPSEC': [ ['build', 'helix-build-slave', 3266, u'SUCCESS'],
                                    ['test', 'helix-test-itl_generic', 1322, u'SUCCESS'],
                                    ['report', 'helix-report', 2381, u'SUCCESS'],
                                    ['retest', 'na', 'na', 'SUCCESS'],
                                    ['rereport', 'na', 'na', 'SUCCESS']],
                   'MCP': [ ['build', 'helix-build-slave', 3268, u'SUCCESS'],
                            ['test', 'helix-test-itl_generic', 1323, u'FAILURE'],
                            ['report', 'helix-report', 2383, u'SUCCESS'],
                            ['retest', 'helix-test-itl_generic', 1325, u'SUCCESS'],
                            ['rereport', 'helix-report', 2386, u'SUCCESS']],
                   'NET_VLAN': [ ['build', 'helix-build-slave', 3270, u'SUCCESS'],
                                 ['test', 'helix-test-itl_generic', 1324, u'SUCCESS'],
                                 ['report', 'helix-report', 2384, u'SUCCESS'],
                                 ['retest', 'na', 'na', 'SUCCESS'],
                                 ['rereport', 'na', 'na', 'SUCCESS']],
                   'NTP': [ ['build', 'helix-build-slave', 3272, u'SUCCESS'],
                            ['test', 'helix-test-itl_generic', 1326, u'SUCCESS'],
                            ['report', 'helix-report', 2395, u'SUCCESS'],
                            ['retest', 'na', 'na', 'SUCCESS'],
                            ['rereport', 'na', 'na', 'SUCCESS']],
                   'QOS': [ ['build', 'helix-build-slave', 3274, u'SUCCESS'],
                            ['test', 'helix-test-itl_generic', 1327, u'FAILURE'],
                            ['report', 'helix-report', 2396, u'SUCCESS'],
                            ['retest', 'helix-test-itl_generic', 1329, u'SUCCESS'],
                            ['rereport', 'helix-report', 2399, u'SUCCESS']],
                   'RADIUS': [ ['build', 'helix-build-slave', 3276, u'SUCCESS'],
                               ['test', 'helix-test-itl_generic', 1328, u'SUCCESS'],
                               ['report', 'helix-report', 2397, u'SUCCESS'],
                               ['retest', 'na', 'na', 'SUCCESS'],
                               ['rereport', 'na', 'na', 'SUCCESS']],
                   'ROHC_IP': [ ['build', 'helix-build-slave', 3278, u'SUCCESS'],
                                ['test', 'helix-test-itl_generic', 1330, u'SUCCESS'],
                                ['report', 'helix-report', 2401, u'SUCCESS'],
                                ['retest', 'na', 'na', 'SUCCESS'],
                                ['rereport', 'na', 'na', 'SUCCESS']],
                   'ROHC_UDP': [ ['build', 'helix-build-slave', 3280, u'SUCCESS'],
                                 ['test', 'helix-test-itl_generic', 1331, u'SUCCESS'],
                                 ['report', 'helix-report', 2404, u'SUCCESS'],
                                 ['retest', 'na', 'na', 'SUCCESS'],
                                 ['rereport', 'na', 'na', 'SUCCESS']],
                   'SECEVENT': [ ['build', 'helix-build-slave', 3282, u'SUCCESS'],
                                 ['test', 'helix-test-itl_generic', 1332, u'SUCCESS'],
                                 ['report', 'helix-report', 2405, u'SUCCESS'],
                                 ['retest', 'na', 'na', 'SUCCESS'],
                                 ['rereport', 'na', 'na', 'SUCCESS']],
                   'SSH': [ ['build', 'helix-build-slave', 3284, u'SUCCESS'],
                            ['test', 'helix-test-itl_generic', 1333, u'SUCCESS'],
                            ['report', 'helix-report', 2406, u'SUCCESS'],
                            ['retest', 'na', 'na', 'SUCCESS'],
                            ['rereport', 'na', 'na', 'SUCCESS']],
                   'SSHCLIENT': [ ['build', 'helix-build-slave', 3286, u'SUCCESS'],
                                  ['test', 'helix-test-itl_generic', 1334, u'SUCCESS'],
                                  ['report', 'helix-report', 2407, u'SUCCESS'],
                                  ['retest', 'na', 'na', 'SUCCESS'],
                                  ['rereport', 'na', 'na', 'SUCCESS']],
                   'USERAUTH_LDAP': [ ['build', 'helix-build-slave', 3287, u'SUCCESS'],
                                      ['test', 'helix-test-itl_generic', 1335, 'INPROGRESS'],
                                      ['report', 'na', 'na', 'na'],
                                      ['retest', 'na', 'na', 'na'],
                                      ['rereport', 'na', 'na', 'na']]},
  'nxp_layerscape_a72': { 'FIREWALL': [ ['build', 'helix-build-slave', 3249, u'SUCCESS'],
                                        ['test', 'helix-test-nxp_layerscape_a72', 554, u'SUCCESS'],
                                        ['report', 'helix-report', 2365, u'SUCCESS'],
                                        ['retest', 'na', 'na', 'SUCCESS'],
                                        ['rereport', 'na', 'na', 'SUCCESS']],
                          'IKE-BASIC': [ ['build', 'helix-build-slave', 3251, u'SUCCESS'],
                                         ['test', 'helix-test-nxp_layerscape_a72', 555, u'SUCCESS'],
                                         ['report', 'helix-report', 2368, u'SUCCESS'],
                                         ['retest', 'na', 'na', 'SUCCESS'],
                                         ['rereport', 'na', 'na', 'SUCCESS']],
                          'IKE-DAEMON': [ ['build', 'helix-build-slave', 3253, u'SUCCESS'],
                                          ['test', 'helix-test-nxp_layerscape_a72', 556, u'SUCCESS'],
                                          ['report', 'helix-report', 2375, u'SUCCESS'],
                                          ['retest', 'na', 'na', 'SUCCESS'],
                                          ['rereport', 'na', 'na', 'SUCCESS']],
                          'IKE-ROHC-IPSEC': [ ['build', 'helix-build-slave', 3255, u'SUCCESS'],
                                              ['test', 'helix-test-nxp_layerscape_a72', 557, u'SUCCESS'],
                                              ['report', 'helix-report', 2377, u'SUCCESS'],
                                              ['retest', 'na', 'na', 'SUCCESS'],
                                              ['rereport', 'na', 'na', 'SUCCESS']],
                          'IPSEC-IPCRYPTO': [ ['build', 'helix-build-slave', 3257, u'SUCCESS'],
                                              ['test', 'helix-test-nxp_layerscape_a72', 558, u'SUCCESS'],
                                              ['report', 'helix-report', 2387, u'SUCCESS'],
                                              ['retest', 'na', 'na', 'SUCCESS'],
                                              ['rereport', 'na', 'na', 'SUCCESS']],
                          'RIP': [ ['build', 'helix-build-slave', 3259, u'SUCCESS'],
                                   ['test', 'helix-test-nxp_layerscape_a72', 559, u'SUCCESS'],
                                   ['report', 'helix-report', 2389, u'SUCCESS'],
                                   ['retest', 'na', 'na', 'SUCCESS'],
                                   ['rereport', 'na', 'na', 'SUCCESS']],
                          'RIPNG': [ ['build', 'helix-build-slave', 3261, u'SUCCESS'],
                                     ['test', 'helix-test-nxp_layerscape_a72', 560, u'SUCCESS'],
                                     ['report', 'helix-report', 2390, u'SUCCESS'],
                                     ['retest', 'na', 'na', 'SUCCESS'],
                                     ['rereport', 'na', 'na', 'SUCCESS']],
                          'SCTP': [ ['build', 'helix-build-slave', 3263, u'SUCCESS'],
                                    ['test', 'helix-test-nxp_layerscape_a72', 561, u'SUCCESS'],
                                    ['report', 'helix-report', 2393, u'SUCCESS'],
                                    ['retest', 'na', 'na', 'SUCCESS'],
                                    ['rereport', 'na', 'na', 'SUCCESS']],
                          'SYSVIEW': [ ['build', 'helix-build-slave', 3265, u'SUCCESS'],
                                       ['test', 'helix-test-nxp_layerscape_a72', 562, u'SUCCESS'],
                                       ['report', 'helix-report', 2394, u'SUCCESS'],
                                       ['retest', 'na', 'na', 'SUCCESS'],
                                       ['rereport', 'na', 'na', 'SUCCESS']]},
  'xlnx_zynqmp': { 'CRYPTO': [ ['build', 'helix-build-slave', 3248, u'SUCCESS'],
                               ['test', 'helix-test-xlnx_zynqmp', 634, u'SUCCESS'],
                               ['report', 'helix-report', 2363, u'SUCCESS'],
                               ['retest', 'na', 'na', 'SUCCESS'],
                               ['rereport', 'na', 'na', 'SUCCESS']],
                   'DHCP': [ ['build', 'helix-build-slave', 3252, u'SUCCESS'],
                             ['test', 'helix-test-xlnx_zynqmp', 635, u'SUCCESS'],
                             ['report', 'helix-report', 2366, u'SUCCESS'],
                             ['retest', 'na', 'na', 'SUCCESS'],
                             ['rereport', 'na', 'na', 'SUCCESS']],
                   'DHCP6': [ ['build', 'helix-build-slave', 3256, u'SUCCESS'],
                              ['test', 'helix-test-xlnx_zynqmp', 636, u'FAILURE'],
                              ['report', 'helix-report', 2367, u'SUCCESS'],
                              ['retest', 'helix-test-xlnx_zynqmp', 638, u'SUCCESS'],
                              ['rereport', 'helix-report', 2371, u'SUCCESS']],
                   'IKE-AUTHENTICATION': [ ['build', 'helix-build-slave', 3260, u'SUCCESS'],
                                           ['test', 'helix-test-xlnx_zynqmp', 637, u'SUCCESS'],
                                           ['report', 'helix-report', 2370, u'SUCCESS'],
                                           ['retest', 'na', 'na', 'SUCCESS'],
                                           ['rereport', 'na', 'na', 'SUCCESS']],
                   'IKE-RACOON': [ ['build', 'helix-build-slave', 3264, u'SUCCESS'],
                                   ['test', 'helix-test-xlnx_zynqmp', 639, u'SUCCESS'],
                                   ['report', 'helix-report', 2372, u'SUCCESS'],
                                   ['retest', 'na', 'na', 'SUCCESS'],
                                   ['rereport', 'na', 'na', 'SUCCESS']],
                   'IKE-SETTINGS': [ ['build', 'helix-build-slave', 3267, u'SUCCESS'],
                                     ['test', 'helix-test-xlnx_zynqmp', 640, u'SUCCESS'],
                                     ['report', 'helix-report', 2376, u'SUCCESS'],
                                     ['retest', 'na', 'na', 'SUCCESS'],
                                     ['rereport', 'na', 'na', 'SUCCESS']],
                   'NAT': [ ['build', 'helix-build-slave', 3269, u'SUCCESS'],
                            ['test', 'helix-test-xlnx_zynqmp', 641, u'SUCCESS'],
                            ['report', 'helix-report', 2378, u'SUCCESS'],
                            ['retest', 'na', 'na', 'SUCCESS'],
                            ['rereport', 'na', 'na', 'SUCCESS']],
                   'PPP': [ ['build', 'helix-build-slave', 3271, u'SUCCESS'],
                            ['test', 'helix-test-xlnx_zynqmp', 642, u'SUCCESS'],
                            ['report', 'helix-report', 2380, u'SUCCESS'],
                            ['retest', 'na', 'na', 'SUCCESS'],
                            ['rereport', 'na', 'na', 'SUCCESS']],
                   'ROHC_ESP': [ ['build', 'helix-build-slave', 3273, u'SUCCESS'],
                                 ['test', 'helix-test-xlnx_zynqmp', 643, u'SUCCESS'],
                                 ['report', 'helix-report', 2382, u'SUCCESS'],
                                 ['retest', 'na', 'na', 'SUCCESS'],
                                 ['rereport', 'na', 'na', 'SUCCESS']],
                   'ROHC_TCP': [ ['build', 'helix-build-slave', 3275, u'SUCCESS'],
                                 ['test', 'helix-test-xlnx_zynqmp', 644, u'SUCCESS'],
                                 ['report', 'helix-report', 2385, u'SUCCESS'],
                                 ['retest', 'na', 'na', 'SUCCESS'],
                                 ['rereport', 'na', 'na', 'SUCCESS']],
                   'SNMP': [ ['build', 'helix-build-slave', 3277, u'SUCCESS'],
                             ['test', 'helix-test-xlnx_zynqmp', 645, u'FAILURE'],
                             ['report', 'helix-report', 2388, u'SUCCESS'],
                             ['retest', 'helix-test-xlnx_zynqmp', 647, u'FAILURE'],
                             ['rereport', 'helix-report', 2392, u'SUCCESS']],
                   'SNTP_CLIENT': [ ['build', 'helix-build-slave', 3279, u'SUCCESS'],
                                    ['test', 'helix-test-xlnx_zynqmp', 646, u'FAILURE'],
                                    ['report', 'helix-report', 2391, u'SUCCESS'],
                                    ['retest', 'helix-test-xlnx_zynqmp', 648, u'SUCCESS'],
                                    ['rereport', 'helix-report', 2398, u'SUCCESS']],
                   'SSL': [ ['build', 'helix-build-slave', 3281, u'SUCCESS'],
                            ['test', 'helix-test-xlnx_zynqmp', 649, u'SUCCESS'],
                            ['report', 'helix-report', 2400, u'SUCCESS'],
                            ['retest', 'na', 'na', 'SUCCESS'],
                            ['rereport', 'na', 'na', 'SUCCESS']],
                   'TFTP': [ ['build', 'helix-build-slave', 3283, u'SUCCESS'],
                             ['test', 'helix-test-xlnx_zynqmp', 650, u'SUCCESS'],
                             ['report', 'helix-report', 2402, u'SUCCESS'],
                             ['retest', 'na', 'na', 'SUCCESS'],
                             ['rereport', 'na', 'na', 'SUCCESS']],
                   'USERDB': [ ['build', 'helix-build-slave', 3285, u'SUCCESS'],
                               ['test', 'helix-test-xlnx_zynqmp', 651, u'SUCCESS'],
                               ['report', 'helix-report', 2403, u'SUCCESS'],
                               ['retest', 'na', 'na', 'SUCCESS'],
                               ['rereport', 'na', 'na', 'SUCCESS']]}}
